export FZF_DEFAULT_OPTS="$FZF_COMMON_OPTS --color=${CURRENT_THEME,,}"
export LG_CONFIG_FILE="$HOME/.config/lazygit/$CURRENT_THEME-config.yml"
export THEME_ZSH_AUTOSUGGEST_HL_STYLE=${CURRENT_THEME}_ZSH_AUTOSUGGEST_HL_STYLE
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=${!THEME_ZSH_AUTOSUGGEST_HL_STYLE}
