export CURRENT_THEME=DARK
export FZF_DEFAULT_OPTS="$FZF_COMMON_OPTS $DARK_FZF_DEFAULT_OPTS"
export LG_CONFIG_FILE="$HOME/.config/lazygit/DARK-config.yml"
export ZSH_AUTOSUGGEST_HIGHDARK_STYLE=$DARK_ZSH_AUTOSUGGEST_HL_STYLE
