export CURRENT_THEME=LIGHT
export FZF_DEFAULT_OPTS=$LIGHT_FZF_DEFAULT_OPTS
export KITTY_THEME=$LIGHT_KITTY_THEME
export LG_CONFIG_FILE=${HOME}/.config/lazygit/LIGHT-config.yml 
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=$LIGHT_ZSH_AUTOSUGGEST_HL_STYLE
